version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: SF_WEATHER_7_25_ONWARD
      POSTGRES_USER: logan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: